# -*- coding: utf-8 -*-
"""day_16_file_handling_syntax.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1XtiGaTn3N9OQ3QT9kxfztbh9zUn4ERq3
"""

# File handling syntaxes


import json
import os


# Section 1: Text File Handling

def text_file_demo():
  """
  Demonstrates how to create, write, read and append to a text file.

  ANALOGY:
  A text file is like a notebook page
  - 'w' mode means you erase the page and rewrite it.
  - 'a' mode means you add new lines at the bottom.
  - 'r' mode means you simply read the page.


  """

  file_name = "example_text.txt"


  # Writing to a text file

  with open(file_name, 'w') as file:
    file.write("Hello! This is the first line.\n")
    file.write("This file teaches text file handling.\n")

  # Why use 'with'?
  # It automatically closes the file, even if errors occur.


  # Reading a text file


  print("\n--- Reading the file---")
  with open(file_name, "a") as file:
    file.write("This line was added later using append mode.\n")


  print("\n--- Reading after append ---")
  with open(file_name, "r") as file:
    print(file.read())

# JSOM FILE HANDLING



def json_file_demo():
  """
  Demonstrates how to create, write, read and update JSON files.


  WHAT IS JSON?

  JSON is a lightweight format for storing structured data.
  It likes Python dictionaries/lists.

  ANALOGY:
  If a text file is a notebook,
  JSON is like a neatly organized spreadsheet with rows/columns



  """

  file_name = "example_data.json"


  # Data to write (Python dict)

  person = {
      "name": "Nikhil",
      "age": 26,
      "city": "Berlin",
      "skills": ["Python", "German A2"]
      }



  # Writing JSON to a file


  with open(file_name, "w") as json_file:
    json.dump(person, json_file, indent=4)
    # indent=4 -> makes the file pretty to read


  # Reading JSON from a file

  print("\n --- Reading JSON file ---")
  with open(file_name, "r") as json_file:
    data = json.load(json_file)
    print(data)



  # Updating JSON data

  print("\n --- Updating JSON ---")
  data['skills'].append("AI Foundations")



  with open(file_name, "w") as json_file:
    json.dump(data, json_file, indent=4)

  print("Updated JSON saved!")

# CONTEXT MANAGERS


def context_manager_demo():
  """
  Shows how context managers work and why they are important.

  ANALOGY:
  A context manager is ike renting a room:
  - You enter the rrom (setup)
  - You use the room
  - When you are done, the room locks itself automatially (cleanup)


  In Python:
  with open("file.txt", "r") as f:
    ... # file is automatically closed afterwards


  """


  print("\n --- Context Manager Example ---")

  # Here we read the first line of the previously created text file
  with open("example_text.txt", "r") as file:
    first_line = file.readline()
    print("First line using context manager:", first_line)

# CLEAN DEMONSTRATION AND EXECUTION

def main():
  print("PYTHON FILE HANDLING")


  text_file_demo()
  json_file_demo()
  context_manager_demo()