# -*- coding: utf-8 -*-
"""day_16_learning_pytest.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1n8gQaNEJ6eH_CAgU3VbzVSYCw85Ijyve
"""

"""
What is Pytest?
Pytest is a tool that tests your Python code automatically.

Think of Pytest like:
- a quality checker for your functions and programs.
- a saftey net that catches bugs early
- a robot that runs all your tests with one command

Pytest helps you build reliable, bug-free and professional Python projects.

"""

# Install Pytest
!pip install pytest pytest-cov

# Create a Folder and a Python File

# Why ?
# - Pytest automatically looks inside the tests/ folder
# - Your real project functions go inside my_project/

import os  # 'os' lets you create folders and work with files

# Create two folders if they don't exist
os.makedirs("my_project", exist_ok=True)   # folder for real code
os.makedirs("tests", exist_ok=True)        # folder for test files

# Make 'my_project' a Python package by adding __init__.py
with open("my_project/__init__.py", "w") as init_file:
    init_file.write("# Makes my_project a package\n")

# Now create a python file called math_tools.py
with open("my_project/math_tools.py", "w") as f:
    f.write("""
def add(a, b):
    # Adds two numbers and returns the result.
    return a + b

def divide(a, b):
    # Divides a by b but must handle division by zero.
    if b == 0:
        # When b is 0, raise an error instead of crashing.
        raise ValueError("Division by zero is not allowed.")
    return a / b
""")

# Write Tests for add()

# A test checks if your function is working correctly.

with open("tests/test_addition.py", "w") as f:
  f.write("""
from content.my_project.math_tools import add

def test_add_positive():
  # 2 + 3 = 5 -> basic case
  assert add(2,3) == 5

def test_add_negative():
  # (-4) + (-6) = -10 -> negative numbers should also work
  assert add(-4, -6) == -10


def test_add_mixed():
  # (-3) + 7 = 4 -> mixing signs
  assert add(-3, 7) == 4



  """)

with open("tests/test_division.py", "w") as f:
  f.write("""
import pytest
from content.my_project.math_tools import divide

def test_divide_normal():
  # Normal division
  assert(10, 2) == 5


def test_divide_by_zero():
  # Testing that our function raises the correct error
  # when dividing by zero
  with pytest.raises(ValueError):
    divide(10, 0)

  """)

import sys
sys.path.append("/content")

!pytest -q /content