# -*- coding: utf-8 -*-
"""day_16_dictionary_practice.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1TSKLa_pKQPwbqOmbSe0fKl5IZLJ9kCOh
"""

# Dictionary from list with custom key



output_dictionary = {
    101: {'name': 'nikhil', 'grade': 'A'},
    102: {'name': 'Alice', 'grade': 'B'}
    }

students = [
    {'id':101, 'name':'nikhil', 'grade': 'A'},
    { 'id':102, 'name':'alice', 'grade': 'B'}
]



custom_dictionary = {}

for student in students:
  if student['id'] not in custom_dictionary:
    custom_dictionary[student['id']] = {}

  custom_dictionary[student['id']].update(student['id'])  # This is an integer and not a dictionary



print(custom_dictionary)

# Correct program for the above problem
students = [
    {'id': 101, 'name': 'nikhil', 'grade': 'A'},
    {'id': 102, 'name': 'alice', 'grade': 'B'}
]




for student in students:
  # Remove the ID from the student data (optional)
  student_data = student.copy() # Create a copy to avoid modifying original

  student_id = student_data.pop('id') # Remove id from the data

  # Direct assignment
  custom_dictionary[student_id] = student_data


print(custom_dictionary)

# Validate dictionay structure
# Given a dictionary, check if it has required keys and correct types
# Required: name (str), 'age'(int), 'email(str)



def validate_dictionary(data):
  error_recorder = []
  if 'name' not in data:
    error_recorder.append("No name key")
  if 'age' not in data:
    error_recorder.append("No age key")
  if 'email' not in data:
    error_recorder.append("No email key")

# Only check types if keys exist (avoid keyError)
  if 'name' in data and type(data['name']) != str:
    error_recorder.append("Name is not string")
  if 'age' in data and type(data['age']) != int:
    error_recorder.append("age is not int")
  if 'email' in data and type(data['email']) != str:
    error_recorder.append("Email is not string")


  return error_recorder

# Test cases
user1 = {'name': 'Alice', 'age': 25, 'email': 'alice@example.com'}
user2 = {'name': 'Bob', 'age': '30', 'email': 'bob@example.com'}  # age is string
user3 = {'name': 'Charlie', 'age': 30}


print(validate_dictionary(user1))  # ✅ True
print(validate_dictionary(user2))  # ❌ False
print(validate_dictionary(user3))  # ❌ False