# -*- coding: utf-8 -*-
"""day_13_dictionary_syntax.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/11-4ipEvhWwxk8LoMTiekmTsYWOKS-mje
"""

"""
Definition:
A dictionary is a collection of key-value oairs.
It stores data like a real-world dictionary:
    Word (key) -> Meaning (value)


KEY PROPERTIES:
1. Keys must be uniq"ue.
2. Keys must be immutable types (str, int, tuple).
3. Values can be anything (numbers, lists, dicts, etc).
4. Dictionaries are unordered

"""

# Basic dictionary
student = {
    "name": "Nikhil",
    "age": 26,
    "course": "Data Science"
}


print("Basic dictionary:", student)



# How to create a dictionary

# Method 1: Curly  braces

d1 = {'a': 1, "b": 2}


# Method 2: dict() constructor

d2 = dict(name="FlyinMonk", country="Nepal")

# Method 3: From list of tuples

d3 = dict([("x", 10), ("y", 20)])


print(d1)
print(d2)
print(d3)



# Accessing values

print(student["name"])    # direct acess
print(student.get("age")) # safe access; returns None if missing

# Example of get() wtih default
print(student.get("height", "Not specified"))
print(student.get("length"))



# Adding and updating

student["height"] = 180   # adding
student["age"] = 27       # updating
student.update({"grade": "A"})    # update method


print(student)




# Deleting items

# pop(key) -> removes and returns value
removed = student.pop("grade")
print("Removed:", removed)


# del -> only removes, no return
del student["height"]

# popitem() -> removes last inserted pair
last = student.popitem()

print("removed last item:", last)
print(student)



# Looping through a dictionary

book = {
    "title": "Naked Statistics",
    "author": "Charles Wheelan",
    "year": 2013
}


print("\nKeys:")
for key in book.keys():
  print(key)

print("\nValues:")
for value in book.values():
  print(value)

print("\nKey and value pair:")
for key, value in book.items():
  print(key, "->", value)



# Checking existence

print("Is 'title' a key?", "title" in book )
print("Is 'nikhil' a value?", "Nikhil" in book.values())

# Dictionary methods (MOST IMPORTANT)


sample = {"x":5, "y": 10}


print("keys():", list(sample.keys()))
print("values():", list(sample.values()))
print("items():", list(sample.items()))

# setdefault

"""
setdefault(key, default):
- If key exists -> return its value
- If not -> insert the key with default value

"""

value = sample.setdefault("z", 99)
print("sample after setdefault:", sample)


# update
sample.update({"x": 100, "w":11})
print("sample after update:", sample)

# NESTED DICTIONARIES

university = {
    "student": {
        "name": "nikhil",
        "age": 26,
        "skills": ["Python", "AI", "GERMAN A2"]
    },
    "address": {
        "city": "berlin",
        "country": "germany"
    }
}


print(university["student"]["skills"][0])

# Dictionary comprehensions

# Powerful, compact way to build dictionaries

# squares
squares = {x: x *x for x in range(1,6)}
print("Squares:", squares)


# conditional dictionary
even = {x: x for x in range(10) if x % 2 == 0}
print("Even dict: ", even)

# Merging dictionaries

d1 = {"a": 1, "b":2}
d2 = {"b": 999, "c": 10}


# Method 1: Unpack
merged = {**d1, **d2}
print("Merged (unpacking):", merged)

# Method 2: union operator
merged2 = d1 | d2
print("Merged (| operator):", merged2)

# Copying dictionaries

# shallow copy vs deep copy

import copy

original = {"name": "Flyin", "marks": [1,2,3]}
shallow = original.copy()
deep = copy.deepcopy(original)

original["marks"].append(4)

print("Original:", original)
print("Shallow copy:", shallow)   # affected because list is shared
print("Deep Copy:", deep)         # not affected