# -*- coding: utf-8 -*-
"""day_15_dictionary_practice.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1cLbudSN2Qiv6mVYIGZSk4vNj25hu2yQm
"""

# Merging multiple dictionaries



def merge_dictionary(*dicts):
  my_dict = {}

  if not dicts:
    return my_dict
  for d in dicts:
    my_dict.update(d)

  return my_dict



# Test the function
result = merge_dictionary(
    {'a': 1, 'b': 2},
    {'c': 3, 'd': 4},
    {'e': 5}
)

print("Merged result:", result)

# Problem 17: Group items by property
# Given: items = [
#     {'name': 'apple', 'category': 'fruit', 'price': 1.2},
#     {'name': 'carrot', 'category': 'vegetable', 'price': 0.8},
#     {'name': 'banana', 'category': 'fruit', 'price': 0.5}
# ]
# Group by category:
# {'fruit': [{'name': 'apple'...}, {'name': 'banana'...}], 'vegetable': [...]}




def group_by_category(items):
  grouped = {} # This will store our final result

  for item in items:
    category = item['category']  # get the category of the current item

    # If this category doesn't exist in our grouped dict yet, create it

    if category not in grouped:
      grouped[category] = []      # create empty list for this category

      # Add the current item to its category list
      grouped[category].append(item)

    return grouped




# Test data
items = [
    {'name': 'apple', 'category': 'fruit', 'price': 1.2},
    {'name': 'carrot', 'category': 'vegetable', 'price': 0.8},
    {'name': 'banana', 'category': 'fruit', 'price': 0.5}
]

# Test the function
result = group_by_category(items)
print("Grouped items:")
print(result)

# Calculate statistics form dictionary

expenses = {'rent':1000, 'food': 500, 'transport': 200, 'utilities': 150}

def expense_statistics(expense):
  total = 0
  for value in expense.values():
    total += value

  max_expense = max([x for x in expense.values()])
  min_expense = min([x for x in expense.values()])

  avg = total / len(expense.values())

  return_dictionary = {"total": total, "maximum expense": max_expense, "minimum expense": min_expense, "average": avg}

  return return_dictionary



print(expense_statistics(expenses))

# Optimized version for above code

expenses = {'rent':1000, 'food': 500, 'transport': 200, 'utilities': 150}

def expense_statistics(expenses):
  """ Calculate statistics from expense dictionary"""

  total = sum(expenses.values())
  max_expense = max(expenses.values())
  min_expense = min(expenses.values())
  avg = total / len(expenses)


  return {
      "total": total,
      "maximum_expense": max_expense,
      "minimum_expense": min_expense,
      "average": round(avg, 2)
  }


print(expense_statistics(expenses))

# Filter and transform

Users = [
    {'name': 'Alice', 'age': 25, 'active': True},
    {'name': 'Bob', 'age': 17, 'active': True},
    {'name': 'Charlie', 'age': 30, 'active': False}
]


def active_users(users):
  active_user = {}

  for user in users:
    if user['age'] >= 18 and user['active'] == True:
      active_user[user['name']] = user['age']

  return active_user



print(active_users(Users))

# Count occurences


text = "Hello world hello python world"

def count_occurences(text):
  occurences_dict = {}
  splitted_text = text.split(" ")


  for word in splitted_text:
    occurences_dict[word] = splitted_text.count(word)

  return occurences_dict



print(count_occurences(text))

# List of dictionaries operations

expenses = [

    {'date': '2024-11-01', 'amount': 50, 'category': 'Food'},
    {'date': '2024-11-02', 'amount': 30, 'category': 'Transport'},
    {'date': '2024-11-03', 'amount': 40, 'category': 'Food'}
 ]



sum_list = []
my_dict = {}
for item in expenses:
  if item['category'] == "Food":
    sum_list.append(item['amount'])



total_sum = sum(sum_list)
print(total_sum)



# More memory efficient

total_sum = 0
for item in expenses:
  if item['category'] == 'Food':
    total_sum += item['amount']

print(total_sum)

# Sort the amount by descending



expenses = [

    {'date': '2024-11-01', 'amount': 50, 'category': 'Food'},
    {'date': '2024-11-02', 'amount': 30, 'category': 'Transport'},
    {'date': '2024-11-03', 'amount': 40, 'category': 'Food'}
 ]


amount = []

for items in expenses:
  amount.append(items['amount'])


sorted_amount = sorted(amount, reverse=True)
print(sorted_amount)



# sorting by date

dates_only = []

for item in expenses:
  dates_only.append(item['date'])



sorted_dates = sorted(dates_only) # Ascending by default
print(sorted_dates)

